spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:mysql://localhost:3306"
      maximum-pool-size: 20
      driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: "jdbc:mysql://localhost:3306"
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    out-of-order: true
    schemas: shop

server:
  port: 8080